#!/bin/bash

echo "Current highest version :"
ls -la releases | grep .zip | awk '{ print $NF }' | tail -1 | sed -e 's/dcwoo\-//g' | sed -e 's/\.zip//g'

echo "Please enter the new version:"
read releaseVersion

cd src

zip -r ../releases/dcwoo-$releaseVersion.zip dcwoo

cd ..

echo "Release created"
ls -la releases | grep .zip | awk '{ print $NF }' | tail -1 

echo "Update the README and the update/latestversion files to reflect the new release"
