#!/bin/zsh

echo "Current highest version :"
currentVersion=$(ls -la releases | grep .zip | awk '{ print $NF }' | tail -1 | sed -e 's/dcwoo\-//g' | sed -e 's/\.zip//g')

echo $currentVersion

echo "Please enter the new version:"
read releaseVersion

sed -i '' -e "s/${currentVersion}/${releaseVersion}/g" update/latestversion
sed -i '' -e "s/${currentVersion}/${releaseVersion}/g" README.md
sed -i '' -e "s/${currentVersion}/${releaseVersion}/g" src/dcwoo/dcwoo.php

cd src

zip -r ../releases/dcwoo-$releaseVersion.zip dcwoo

cd ../

echo "Release created"

ls -la releases | grep .zip | awk '{ print $NF }' | tail -1 

echo "Version updated"

echo "Release ${releaseVersion} created"